apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigSync
metadata:
  name: test
  namespace: platform-requests
spec:
  name: test
  targetNamespace: vcluster-test
  kubeconfigSyncJobName: vcluster-test-kubeconfig-sync
  onepasswordItem: vcluster-test-kubeconfig
  hostname: test.integratn.tech
  apiPort: 8443
  serverUrl: https://test.integratn.tech:8443
