apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigExternalSecret
metadata:
  name: test
  namespace: platform-requests
spec:
  name: test
  targetNamespace: vcluster-test
  onepasswordItem: vcluster-test-kubeconfig
