apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigSync
metadata:
  name: test4
  namespace: platform-requests
spec:
  name: test4
  targetNamespace: vcluster-test-4
  kubeconfigSyncJobName: vcluster-test4-kubeconfig-sync-20260120200426
  onepasswordItem: vcluster-test4-kubeconfig
  hostname: test4.integratn.tech
  apiPort: 443
  serverUrl: https://test4.integratn.tech:443
