apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigExternalSecret
metadata:
  name: test4
  namespace: platform-requests
spec:
  name: test4
  targetNamespace: vcluster-test-4
  onepasswordItem: vcluster-test4-kubeconfig
