apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-test-vcluster-values
  namespace: vcluster-prod-test
data:
  values.yaml: |
    {controlPlane: {distro: {k8s: {enabled: true, version: "v1.34.3"}}, statefulSet: {highAvailability: {replicas: 1}, persistence: {volumeClaim: {enabled: true, size: "10Gi"}}, resources: {requests: {cpu: "500m", memory: "1Gi"}, limits: {cpu: "2", memory: "2Gi"}}}, coredns: {deployment: {replicas: 1}}, service: {enabled: true, annotations: {external-dns.alpha.kubernetes.io/hostname: "prod-test.integratn.tech"}, spec: {type: LoadBalancer, loadBalancerIP: "10.0.7.100", ports: [{name: https, port: 8443, targetPort: 8443, protocol: TCP}]}}}, networking: {advanced: {clusterDomain: "cluster.local"}}, sync: {toHost: {pods: {enabled: true}}}}
