apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/component: kubeconfig-sync
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: external-secret
    kratix.io/promise-name: argocd-cluster-registration
    kratix.io/resource-name: test
  name: test-onepassword-token
  namespace: test
spec:
  data:
  - remoteRef:
      key: onepassword-access-token
      property: credential
    secretKey: token
  - remoteRef:
      key: onepassword-access-token
      property: vault
    secretKey: vault
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: test-onepassword-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: kubeconfig-sync
    kratix.io/promise-name: argocd-cluster-registration
    kratix.io/resource-name: test
  name: test-kubeconfig-sync
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: kubeconfig-sync
    kratix.io/promise-name: argocd-cluster-registration
    kratix.io/resource-name: test
  name: test-kubeconfig-sync
  namespace: test
rules:
- apiGroups:
  - ""
  resourceNames:
  - vc-test
  - test-onepassword-token
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: kubeconfig-sync
    kratix.io/promise-name: argocd-cluster-registration
    kratix.io/resource-name: test
  name: test-kubeconfig-sync
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-kubeconfig-sync
subjects:
- kind: ServiceAccount
  name: test-kubeconfig-sync
  namespace: test
