apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vc-media
  namespace: argocd
  annotations:
    {}


spec:
  project: vcluster-media
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.30.4
    helm:
      releaseName: media
      valuesObject:
        controlPlane:
          backingStore:
            etcd:
              deploy:
                enabled: true
                statefulSet:
                  highAvailability:
                    replicas: 3
          coredns:
            enabled: false
          distro:
            k8s:
              enabled: true
          service:
            annotations: {}
            type: LoadBalancer
          statefulSet:
            highAvailability:
              replicas: 3
        integrations:
          externalDNS:
            domain: media.integratn.tech
            enabled: true
            sync: enabled
        networking:
          replicateServices:
            fromHost:
              - from: default/kubernetes
                to: default/kubernetes
        persistence:
          volumeClaim:
            enabled: true
            size: 10Gi
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        sync:
          fromHost:
            ingressClasses:
              enabled: true
            storageClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: true
            persistentVolumeClaims:
              enabled: true
            services:
              enabled: true
            storageClasses:
              enabled: true
        telemetry:
          disabled: true
        vcluster:
          image:
            tag: v1.34.3
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-media
  syncPolicy:
    {}
