apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigExternalSecret
metadata:
  name: test3
  namespace: platform-requests
spec:
  name: test3
  targetNamespace: vcluster-test-3
  onepasswordItem: vcluster-test3-kubeconfig
