apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigSync
metadata:
  name: test3
  namespace: platform-requests
spec:
  name: test3
  targetNamespace: vcluster-test-3
  kubeconfigSyncJobName: vcluster-test3-kubeconfig-sync-20260120200426
  onepasswordItem: vcluster-test3-kubeconfig
  hostname: test3.integratn.tech
  apiPort: 8443
  serverUrl: https://test3.integratn.tech:8443
