apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/component: kubeconfig
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: external-secret
    kratix.io/promise-name: argocd-cluster-registration
    kratix.io/resource-name: demo
  name: demo-kubeconfig
  namespace: demo
spec:
  dataFrom:
  - extract:
      key: demo-kubeconfig
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: demo-kubeconfig-external
    template:
      data:
        config: |
          {{ .kubeconfig }}
      engineVersion: v2
