apiVersion: platform.integratn.tech/v1alpha1
kind: ArgoCDApplication
metadata:
  name: media
  namespace: platform-requests
  labels:
    app.kubernetes.io/name: argocd-application
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: media
spec:
  namespace: argocd
  name: vc-media
  project: vcluster-media
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-media
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.31.0
    helm:
      releaseName: media
      valuesObject:
        controlPlane:
          distro:
            k8s:
              enabled: true
              image:
                tag: v1.34.3
          statefulSet:
            highAvailability:
              replicas: 3
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: 2
                memory: 2Gi
            persistence:
              volumeClaim:
                enabled: true
                size: 10Gi
          backingStore:
            database:
              embedded:
                enabled: false
            etcd:
              deploy:
                enabled: true
                statefulSet:
                  highAvailability:
                    replicas: 3
          coredns:
            enabled: false
          ingress:
            enabled: true
            host: media.integratn.tech
          service:
            annotations:
              io.cilium/lb-ipam-ips: 
        networking:
          advanced:
            clusterDomain: ""
          replicateServices:
            fromHost:
              - from: default/kubernetes
                to: default/kubernetes
        sync:
          toHost:
            ingresses:
              enabled: true
            services:
              enabled: true
            persistentVolumeClaims:
              enabled: true
          fromHost:
            ingressClasses:
              enabled: true
            storageClasses:
              enabled: true
        telemetry:
          enabled: false

