apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vc-media
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: vcluster-media
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.31.0
    helm:
      releaseName: media
      valuesObject:
        controlPlane:
          statefulSet:
            persistence:
              addVolumeMounts:
                - mountPath: /pki
                  name: etcd-certs
                  readOnly: true
              addVolumes:
                - name: etcd-certs
                  secret:
                    secretName: media-certs
        deploy:
          metallb:
            enabled: true
        integrations:
          certManager:
            enabled: true
            sync:
              fromHost:
                clusterIssuers:
                  enabled: true
                  selector:
                    labels:
                      integratn.tech/cluster-issuer: letsencrypt-prod
          externalSecrets:
            enabled: true
            sync:
              fromHost:
                clusterStores:
                  enabled: true
                  selector:
                    matchLabels:
                      integratn.tech/cluster-secret-store: onepassword-store
            webhook:
              enabled: true
          metricsServer:
            enabled: true
        logging:
          encoding: json
        networking:
          advanced:
            clusterDomain: cluster.local
          replicateServices:
            fromHost:
              - from: default/kubernetes
                to: default/kubernetes
        rbac:
          clusterRole:
            enabled: true
            extraRules:
              - apiGroups:
                  - ""
                resourceNames:
                  - eso-onepassword-token
                resources:
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
        sync:
          fromHost:
            ingressClasses:
              enabled: false
            secrets:
              enabled: true
              mappings:
                byName:
                  external-secrets/eso-onepassword-token: external-secrets/eso-onepassword-token
            storageClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: false
            networkPolicies:
              enabled: false
            persistentVolumes:
              enabled: true
            pods:
              enabled: true
        telemetry:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
