apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigExternalSecret
metadata:
  name: test2
  namespace: platform-requests
spec:
  name: test2
  targetNamespace: vcluster-test-2
  onepasswordItem: vcluster-test2-kubeconfig
