apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigSync
metadata:
  name: test2
  namespace: platform-requests
spec:
  name: test2
  targetNamespace: vcluster-test-2
  kubeconfigSyncJobName: vcluster-test2-kubeconfig-sync-20260120200426
  onepasswordItem: vcluster-test2-kubeconfig
  hostname: test2.integratn.tech
  apiPort: 443
  serverUrl: https://test2.integratn.tech:443
