apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/component: kubeconfig-sync
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: external-secret
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: vcluster-media
  name: vcluster-media-onepassword-token
  namespace: vcluster-media
spec:
  data:
  - remoteRef:
      key: onepassword-access-token
      property: credential
    secretKey: token
  - remoteRef:
      key: onepassword-access-token
      property: vault
    secretKey: vault
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: vcluster-vcluster-media-onepassword-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: kubeconfig-sync
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: vcluster-media
  name: vcluster-media-kubeconfig-sync
  namespace: vcluster-media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: kubeconfig-sync
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: vcluster-media
  name: vcluster-media-kubeconfig-sync
  namespace: vcluster-media
rules:
- apiGroups:
  - ""
  resourceNames:
  - vc-vcluster-media
  - vcluster-vcluster-media-onepassword-token
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: kubeconfig-sync
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: vcluster-media
  name: vcluster-media-kubeconfig-sync
  namespace: vcluster-media
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcluster-media-kubeconfig-sync
subjects:
- kind: ServiceAccount
  name: vcluster-media-kubeconfig-sync
  namespace: vcluster-media
