apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vcluster-media-kubeconfig
  namespace: vcluster-media
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/component: kubeconfig
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: vcluster-media
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: vcluster-vcluster-media-kubeconfig-external
    template:
      engineVersion: v2
      data:
        config: |
          {{ .kubeconfig }}
  dataFrom:
    - extract:
        key: vcluster-vcluster-media-kubeconfig
  refreshInterval: 15m
