apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigSync
metadata:
  name: media
  namespace: platform-requests
spec:
  name: media
  targetNamespace: vcluster-media
  kubeconfigSyncJobName: vcluster-media-kubeconfig-sync
  onepasswordItem: vcluster-media-kubeconfig
  hostname: media.integratn.tech
  apiPort: 443
  serverUrl: https://media.integratn.tech:443
