apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterKubeconfigExternalSecret
metadata:
  name: media
  namespace: platform-requests
spec:
  name: media
  targetNamespace: vcluster-media
  onepasswordItem: vcluster-media-kubeconfig
